name: image_delete_demo
description: "A new Flutter project."
publish_to: 'none'


scripts: 
  gen: "dart run build_runner watch"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_manager: ^3.6.4
  permission_handler: ^12.0.0+1
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  appinio_swiper: ^2.1.1
  photo_manager_image_provider: ^2.2.0
  flutter_animate: ^4.5.2
  flutter_feather_icons: ^2.0.0+1
  pixelarticons: ^0.4.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  freezed_annotation: "^2.4.4"
  json_annotation: "^4.9.0"
  auto_size_text: "^3.0.0"
  gap: "^3.0.1"
  flip_card: "^0.7.0"
  auto_route: "^9.2.2"
  mutex: "^3.1.0"
  package_info_plus: "^8.1.2"
  rate_limiter: "^1.0.0"
  smooth_sheets: "^0.10.2"
  path_provider: "^2.1.5"
  app_links: "^6.3.3"
  mailto: "^2.0.0"
  url_launcher: "^6.3.1"
  flutter_native_splash: "2.4.4"
  collection: "^1.19.0"
  auto_size_text_field: "^2.2.4"
  fading_edge_scrollview: "^4.1.1"
  table_calendar: "^3.2.0"
  visibility_detector: "^0.4.0+2"
  flutter_shaders: "^0.1.3"
  path: "^1.9.0"
  timezone: "^0.10.0"
  hydrated_bloc: "^10.0.0"
  bloc: "^9.0.0"
  toastification: "^2.3.0"
  get_it: "^8.0.3"
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: "^9.0.0"
  build_runner: "^2.4.9"
  freezed: "^2.4.7"
  json_serializable: "^6.7.1"

flutter:
  uses-material-design: true